const state = {
    events: [],
    savedEvents: [],
    name: "",
    cityInput: "",
    cityResult: "",
    cityLat: "",
    cityLng: "",
    date: "",
    time: "",
    localTime: "",
    utcTime: "",
    timeZoneName: "",
    weather: "",
    news: "",
    sun: "",
    season: "",
    lunarPosition: "",
    lunarSector: "",
    lunarPhase: "",
    mercuryPosition: "",
    mercurySector: "",
    mercuryMotion: "",
    venusPosition: "",
    venusSector: "",
    venusMotion: "",
    marsPosition: "",
    marsSector: "",
    marsMotion: "",
    jupiterPosition: "",
    jupiterSector: "",
    jupiterMotion: "",
    saturnPosition: "",
    saturnSector: "",
    saturnMotion: "",
    uranusPosition: "",
    uranusSector: "",
    uranusMotion: "",
    neptunePosition: "",
    neptuneSector: "",
    neptuneMotion: "",
    plutoPosition: "",
    plutoSector: "",
    plutoMotion: "",
    registerFormName: "",
    registerFormPassword: "",
    registerFormPasswordConfirm: "",
    loginFormName: "",
    loginFormPassword: "",
    loginName: "",
    loginUserId: "",
    removeUserText: "Click to Remove User",
    removeUserColor: "removeUserGrey"
};

export default state;